---
# vars file for jinja2_spine
  #nxos_provider:
  username: "{{ user }}"
  password: "{{ pwd }}"
  timeout: 100
  host: "{{ inventory_hostname }}"
  asn: 65401
  bgp_neighbors:
  -  remote_as: 65401
     neighbor: 100.66.0.3
     update_source: Loopback0
  -  remote_as: 65401
     neighbor: 100.66.0.4
     update_source: Loopback0
  -  remote_as: 65401
     neighbor: 100.66.0.7
     update_source: Loopback0
  #L3_interfaces:
  #-  interface: Ethernet 1/1
  #-  interface: Ethernet 1/2
  #-  interface: Ethernet 1/3
  #-  interface: loopback 0
  #-  interface: loopback 254
  #s1_loopback: 192.168.0.6
  #s2_loopback: 192.168.0.7
  # vars file for generate-L2L3VNIs
  l2vni_vlans:
  - { vlan_id: 2300, vni_id: 30000, addr: 172.10.10.1, mask: 24, mcast_grp: 239.0.0.11, vrf: prod-internal }
#  - { vlan_id: 2301, vni_id: 30001, addr: 172.20.12.1, mask: 24, mcast_grp: 239.0.0.12, vrf: Tenant-1 }

  l3vni_vlans:
  - { vlan_id: 2000, vni_id: 50000, vrf: prod-internal }
# - { vlan_id: 2001, vni_id: 50001, vrf: dmz-servers }
  