---
# tasks file for jinja2_leaf
  - name: Generate Leaf Config
    template: 
      src: roles/jinja2_leaf/templates/leaf.j2
      dest: roles/jinja2_leaf/files/{{inventory_hostname}}.cfg
  - name: Push Leaf Config
    nxos_config:
      src: roles/jinja2_leaf/files/{{inventory_hostname}}.cfg
  - name: Generate Leaf VNI Config
    template:
      src: roles/jinja2_leaf/templates/VNIs.j2
      dest: roles/jinja2_leaf/files/{{inventory_hostname}}-VNIs.cfg
  - name: Push Leaf VNI Config
    nxos_config:
      src: roles/jinja2_leaf/files/{{inventory_hostname}}-VNIs.cfg
