---
# vars file for jinja2_leaf
  timeout: 100
  host: "{{ inventory_hostname }}"
  asn: 65401
  bgp_neighbors:  #Spine iBGP neigbors
  -  remote_as: 65401
     neighbor: 100.66.0.5
     update_source: Loopback0
  #rp_address: 192.168.8.1
# vars file for generate-L2L3VNIs
  l2vni_vlans:
  - { vlan_id: 2300, vni_id: 30000, addr: 172.10.10.1, mask: 24, mcast_grp: 239.0.0.11, vrf: prod-internal, name: prod-internal }
#  - { vlan_id: 2301, vni_id: 30001, addr: 172.20.12.1, mask: 24, mcast_grp: 239.0.0.12, vrf: Tenant-1 }

  l3vni_vlans:
  - { vlan_id: 2000, vni_id: 50000, vrf: prod-internal, name: prod-internal }
# - { vlan_id: 2001, vni_id: 50001, vrf: dmz-servers }
  