---
# vars file for jinja2_leaf
  #nxos_provider:
  username: "{{ user }}"
  password: "{{ pwd }}"
  timeout: 100
  host: "{{ inventory_hostname }}"
  asn: 65401
  bgp_neighbors:
  -  remote_as: 65401
     neighbor: 100.66.0.5
     update_source: Loopback0
  #rp_address: 192.168.8.1
  #L3_interfaces:
  #-  interface: Ethernet 1/1
  #-  interface: Ethernet 1/2
  #-  interface: Ethernet 1/3
  #-  interface: loopback 0
  #-  interface: loopback 1
  L2VNI:
  -  vlan_id: 140
     vni: 50140
     ip_add: 172.21.140.1
     mask: 24
     vlan_name: L2-VNI-140-Tenant1
     mcast: 239.0.0.140
  -  vlan_id: 141
     vni: 50141
     ip_add: 172.21.141.1
     mask: 24
     vlan_name: L2-VNI-141-Tenant1
     mcast: 239.0.0.141
  L3VNI:
  -  vlan_id: 999
     vlan_name: L3-VNI-999-Tenant1
     vni: 50999
# vars file for generate-L2L3VNIs
  l2vni_vlans:
  - { vlan_id: 2300, vni_id: 30000, addr: 172.10.10.1, mask: 24, mcast_grp: 239.0.0.11, vrf: prod-internal }
#  - { vlan_id: 2301, vni_id: 30001, addr: 172.20.12.1, mask: 24, mcast_grp: 239.0.0.12, vrf: Tenant-1 }

  l3vni_vlans:
  - { vlan_id: 2000, vni_id: 50000, vrf: prod-internal }
# - { vlan_id: 2001, vni_id: 50001, vrf: dmz-servers }
  